#!/usr/bin/env bash
# aggregate-report.sh
# Merges the secrets scan and dependency audit results into one human-readable
# summary, writes it to $GITHUB_STEP_SUMMARY when running in Actions, and sets
# the overall pipeline exit status.
#
# Usage: ./aggregate-report.sh <report-dir>
# Exit codes: 0 = clean, 1 = one or more checks failed

set -uo pipefail

REPORT_DIR="${1:-./security-reports}"
SECRETS_JSON="$REPORT_DIR/secrets-report.json"
DEPS_JSON="$REPORT_DIR/deps-report.json"
SUMMARY_FILE="$REPORT_DIR/summary.md"

if ! command -v jq >/dev/null 2>&1; then
  echo "==> jq not found, installing..."
  (sudo apt-get update -qq && sudo apt-get install -y -qq jq) >/dev/null 2>&1 || {
    echo "❌ Could not install jq — cannot parse JSON reports."
    exit 2
  }
fi

SECRETS_COUNT=0
DEPS_COUNT=0

if [ -f "$SECRETS_JSON" ]; then
  SECRETS_COUNT="$(jq 'if type == "array" then length else 0 end' "$SECRETS_JSON" 2>/dev/null || echo 0)"
fi

if [ -f "$DEPS_JSON" ]; then
  DEPS_COUNT="$(jq '[.dependencies[]? | select((.vulns // []) | length > 0)] | length' "$DEPS_JSON" 2>/dev/null || echo 0)"
fi

{
  echo "# Security Pipeline Summary"
  echo
  echo "| Check | Findings | Status |"
  echo "|---|---|---|"
  if [ "$SECRETS_COUNT" -gt 0 ]; then
    echo "| Hardcoded secrets | $SECRETS_COUNT | ❌ Fail |"
  else
    echo "| Hardcoded secrets | 0 | ✅ Pass |"
  fi
  if [ "$DEPS_COUNT" -gt 0 ]; then
    echo "| Vulnerable dependencies | $DEPS_COUNT | ❌ Fail |"
  else
    echo "| Vulnerable dependencies | 0 | ✅ Pass |"
  fi
  echo
  echo "_Generated by [security-pipeline](https://github.com/milobzb/security-pipeline)._"
} | tee "$SUMMARY_FILE"

if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
  cat "$SUMMARY_FILE" >> "$GITHUB_STEP_SUMMARY"
fi

if [ "$SECRETS_COUNT" -gt 0 ] || [ "$DEPS_COUNT" -gt 0 ]; then
  echo "Pipeline result: FAIL"
  exit 1
fi

echo "Pipeline result: PASS"
exit 0
